apiVersion: v1
kind: Service
metadata:
  name: domain-monitor
  namespace: domain-monitor
  labels:
    app.kubernetes.io/name: domain-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: domain-monitor
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
